### ISSUE TITLE
Index error in to_html.py

### ISSUE THREAD

**Issue by SchwarzMarek** [jttoivon/MODER#2]
Hello,
I'm trying out the `moder` and I'm having issues with `to_html.py` script

I have two monomers and I've specified that pairing should be 0-1 (option `--cob 0-1`) if that is relevant.
```
...
/home/marek/miniconda3/envs/moder/lib/python2.7/site-packages/matplotlib/cbook/deprecation.py:107: MatplotlibDeprecationWarning: Passing one of 'on', 'true', 'off', 'false' as a boolean is deprecated; use an actual boolean (True/False) instead.
  warnings.warn(message, mplDeprecation, stacklevel=1)
Traceback (most recent call last):
  File "/home/marek/miniconda3/envs/moder/bin/to_html.py", line 1414, in <module>
    make_better_table(f, link_table, [""]+range(dmin[i], dmax[i]+1), orients, htmlclass="ppmtable")
IndexError: list index out of range
```

Also I would like to ask if there is a way to specify custom background for the sequences? If yes, then how?
Thank you

**Comment by jttoivon** [comment]
Hi,

Sorry for the late response. And thanks for the feedback!
The bug should now be fixed. Please do 'git pull' and 'make'.

Unfortunately there is no way to specify custom background as
the algorithm learns the background model from data when
it runs.

By the way, there is a new version called MODER2 available
from https://github.com/jttoivon/moder2
This newer version can also learn models of order 1, in addition
to PPM models (order 0). New development mostly happens
in the new repository.
